### ISSUE TITLE
Add a `host` field to log records

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/python-logging-humio#7]
A common usage of Humio (or Falcon LogScale, as I think it's now called) to aggregate logs from multiple hosts into a single repository.

I suggest the emitted log records from the Humio handlers should be imbued with a `host` attribute, so that it will be possible to separate log records from different hosts.

The fully qualified domain name of the host (from `socket.getfqden()`) should be used as the value.

I guess there are two ways to go about this, either:

1. Always add the `host` attribute to the log record in each of the two provided formatters

or

2. Add a separate Filter class that does nothing but add the `host` attribute to each log record, and update the README to show how the filter can be selectively attached to the log handlers if the user wishes to have the `host` attribute.

**Comment by hmpf** [comment]
There is already support for emitting a tag with the hostname, by setting "add_host_tag" to True when configuring the handler. See the readme.

**Comment by lunkwill42** [comment]
Bah, you told me this morning adding a hostname was easy. You didn't specify that it was already supported out-of-the-box :-D
